#variable_texto = "Agenda " # String - Texto
#print(variable_texto.upper())
#print(variable_texto.lower())
#print(variable_texto.upper().find(str.lower("GE")))
#nueva_variable_texto_reemplazo = variable_texto.replace("Agenda","Citas Medicas Especialistas")
#print (variable_texto.replace("Agenda","Citas Medicas "))
#print(variable_texto)
#print(nueva_variable_texto_reemplazo)
#print("Agenda" in nueva_variable_texto_reemplazo)
#print("Agenda" in variable_texto)
dato_ingresado = input("Digite su usuario:")
print (type(dato_ingresado))
#valor = 18 int(dato_ingresado)
#print ("valor * 3 " )
